---
- hosts: localhost
  connection: localhost

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "devops-cicd"
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
    loop:
      - { image: "ami-078264b8ba71bc45e", name: "manange-node-1" }
      - { image: "ami-0dee22c13ea7a9a67", name: "manange-node-2" }
      - { image: "ami-0dee22c13ea7a9a67", name: "manange-node-3"}
